### ISSUE TITLE
IndoorAtlas SDK isn't bundled with the sample project

### ISSUE THREAD

**Issue by timbornholdt** [IndoorAtlas/ios-sdk-examples#1]
I don't see a copy of IndoorAtlas.framework anywhere in the sample project, and when I go to compile the app, Xcode complains that it can't find `<IndoorAtlas/IALocationManager.h>`.

**Comment by ntorppa** [comment]
Hi,

Please read instructions to get SDK framework from;  http://docs.indooratlas.com/ios/getting-started.html

Br,
Niko Torppa

**Comment by yisu12345** [comment]
How to download IndoorAtlas.framework?I had been searched in  http://docs.indooratlas.com/ios/getting-started.html but not found :(

**Comment by ntorppa** [comment]
Hi,

Use CocoaPods to download IndoorAtlas framework for your sample project;
http://docs.indooratlas.com/ios/getting-started.html

Or use manual download steps;
http://docs.indooratlas.com/ios/manual-installation.html

**Comment by josepharunjoseph** [comment]
Hi,

I tried with CocoaPods in latest sdk example but  it gave me error when I try to install cocoapods in terminal.
 I already Post this issue in **CocoaPods-Specs**. But no response from Support team. And also I am not satisfy the chat response from support team.
Check this link :https://github.com/IndoorAtlas/CocoaPods-Specs/issues/1
