### ISSUE TITLE
Way Finding feature

### ISSUE THREAD

**Issue by Priyanka-Razdan** [IndoorAtlas/ios-sdk-examples#12]
I have seen Way-finding in the use case of Indoor Atlas.
Could you please provide an example for the way finding feature too. It will be really helpful.

Thanks
Priyanka Razdan

**Comment by oseiskar** [comment]
Wayfinding is currently not included in the core IndoorAtlas SDK but is an additional service offered by third parties. We will clarify this further in the near future.
