### ISSUE TITLE
Indoor Atlas examples

### ISSUE THREAD

**Issue by Bramnouwen** [IndoorAtlas/ios-sdk-examples#2]
Hi,

I am using the IndoorAtlas/ios-sdk-examples, but when I run it it seems to get stuck at the waiting for 
location data.... Can someone help me?

**Comment by SeppoTomperi** [comment]
See http://docs.indooratlas.com/ios/dev-guide/frequently-asked.html

Also remember that you must map the floor plan before it is possible to position on it. Android phone is required for mapping:

https://play.google.com/store/apps/details?id=com.indooratlas.android.apps.jaywalker&hl=en
