### ISSUE TITLE
didUpdateLocations method didn't call

### ISSUE THREAD

**Issue by saramankaramata** [IndoorAtlas/ios-sdk-examples#22]
Hello,

i am using indooratls SDK 3.0.1, but  didUpdateLocations method called 2 time, then not call.
I also used this example, but its also not work.
Its already work in SDK version 2.9.3,

Thanks.

**Comment by matti-ida** [comment]
Hi,

please check our knowledge base at https://indooratlas.freshdesk.com/support/home
Troubleshooting check list is at https://indooratlas.freshdesk.com/support/solutions/folders/36000173652

Thanks.
