### ISSUE TITLE
DidEnterRegion is not being called

### ISSUE THREAD

**Issue by VinayGTHub** [IndoorAtlas/ios-sdk-examples#23]
func indoorLocationManager(_ manager: IALocationManager, didEnter region: IARegion)  is not getting called. I have tried 3.0.2 and 3.0.3 both version.

**Comment by matti-ida** [comment]
Hi,

please check our knowledge base at https://indooratlas.freshdesk.com/support/home
Troubleshooting check list is at https://indooratlas.freshdesk.com/support/solutions/folders/36000173652

Thanks.
