### ISSUE TITLE
Floor not changing in iOS

### ISSUE THREAD

**Issue by vector-solutions** [IndoorAtlas/ios-sdk-examples#29]
We have implemented the IndoorAtlas SDK on both platforms i.e., android & iOS. The problem is that the floor doesn't change on iOS while its working perfectly fine on android device. Can you please guide us on it.

**Comment by matti-ida** [comment]
Hi,

for general support please use our support portal at https://indooratlas.freshdesk.com/support/solutions/36000112112

For iOS, beacons are a requirement, see https://indooratlas.freshdesk.com/support/solutions/articles/36000050501-why-to-use-beacons-with-indooratlas-

Also make sure you have the required permissions as described here: https://indooratlas.freshdesk.com/support/solutions/articles/36000051274-setup-positioning-with-ios

For more troubleshooting use the Map Creator app as described here and submit a ticket with the trace ids in the support portal: https://indooratlas.freshdesk.com/support/solutions/articles/36000050555-troubleshooting-positioning-getting-the-trace-id

Thanks.

- Matti

**Comment by matti-ida** [comment]
You can also get the traceId in your application.

For iOS example see: https://github.com/IndoorAtlas/ios-sdk-examples/blob/master/example/src/Examples/AppleMapsOverlayViewController.m#L247

And for Android: https://github.com/IndoorAtlas/android-sdk-examples/blob/master/Basic/src/main/java/com/indooratlas/android/sdk/examples/mapsoverlay/MapsOverlayActivity.java#L258
